sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs-1'
  - 'iojs-2'
  - iojs
script: "npm run jshint && npm run test-travis && npm run test-optimized"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
