sudo: false
os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
script:
  - 'npm run ci'
after_script:
  - 'npm i codecov && codecov'
  - 'node benchmark/map.js'
  - 'node benchmark/array_splice.js'
