sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
script:
  - 'npm run ci'
after_script:
  - 'npm i codecov && codecov'
  - 'node benchmark/map.js'
  - 'node benchmark/array_splice.js'
